# Generated by Django 3.0.3 on 2020-03-26 13:06

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Article name.')),
                ('description', models.TextField(verbose_name='Article text.')),
                ('author', models.CharField(max_length=20, verbose_name='Author name.')),
                ('image', models.ImageField(upload_to=blog.models.Article.path_uploa, verbose_name='Article image.')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Post time.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active article.')),
            ],
            options={
                'verbose_name': 'Article for blog',
                'verbose_name_plural': 'Articles for blog',
                'db_table': 'articles',
            },
        ),
    ]
