# Generated by Django 3.0.4 on 2020-03-26 08:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Article title')),
                ('date', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=250, verbose_name='Comment')),
                ('access', models.CharField(choices=[['access_admin', 'access for admin'], ['access_user', 'access for user']], max_length=50, verbose_name='Access blogs ')),
                ('image', models.ImageField(upload_to=blog.models.Article.path_upload, verbose_name='Blog image.')),
            ],
            options={
                'verbose_name': 'Article for blog',
                'verbose_name_plural': 'Arcticles for blog',
                'db_table': 'arcticles',
            },
        ),
    ]
