# Generated by Django 3.0.4 on 2020-03-31 10:33

import blog.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200326_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default=django.utils.timezone.now, help_text="Author's name", max_length=100, verbose_name="Author's name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Publication date', verbose_name='Publication date'),
        ),
        migrations.AddField(
            model_name='comments',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=blog.models.Comments.path_upload, verbose_name="Author's image"),
            preserve_default=False,
        ),
    ]
