# Generated by Django 3.0.3 on 2020-03-12 18:15

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DressSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Size name.')),
                ('asia', models.CharField(choices=[['S', 'Small'], ['S', 'Small'], ['M', 'Middle'], ['L', 'Large'], ['L', 'Large'], ['XL', 'Extra Large'], ['XXL', '2 Extra Large'], ['XXL', '2 Extra Large'], ['3XL', '3 Extra Large']], max_length=3, verbose_name='Asia size.')),
                ('russia', models.SmallIntegerField(validators=[shop.models.rus_size_valid], verbose_name='Russian size.')),
                ('internetional', models.CharField(choices=[['XXS', '2 Extra Small'], ['XS', 'Extra Small'], ['S', 'Small'], ['M', 'Middle'], ['L', 'Large'], ['XL', 'Extra Large'], ['XXL', '2 Extra Large'], ['3XL', '3 Extra Large'], ['4XL', '4 Extra Large']], max_length=3, verbose_name='Internetional size.')),
            ],
            options={
                'verbose_name': 'Dress sizes.',
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Product name.')),
                ('price', models.FloatField(validators=[shop.models.price_valid], verbose_name='Product price.')),
                ('sale', models.FloatField(null=True, validators=[shop.models.sale_price], verbose_name='Product sale.')),
                ('description', models.TextField(verbose_name='Product description')),
                ('count', models.PositiveSmallIntegerField(verbose_name='Counts dresses.')),
                ('image', models.ImageField(upload_to=shop.models.Product.path_upload, verbose_name='Product image.')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active.')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.DressSize')),
            ],
            options={
                'verbose_name': 'Product for shop.',
                'db_table': 'products',
            },
        ),
    ]
